version: 1
labels:
  - label: "WIP"
    title: "^WIP:.*"
  - label: "feature"
    branch: "^(feature|Feature)/.*"
  - label: "bugfix"
    branch: "^(bugfix|Bugfix)/.*"
  - label: "enh"
    branch: "^(enhance|Enhance)/.*"
  - label: "refactor"
    branch: "^(refactor|Refactor)/*"
  - label: "docs"
    branch: "^(docs|Docs)/*"
  - label: "need-to-change-branch-name"
    branch: "^(?!^(feature|Feature)/.*$)(?!^(bugfix|Bugfix)/.*$)(?!^(enhance|Enhance)/.*$)(?!^(style|Style)/.*$)(?!^(docs|Docs)/.*$).*$"
